// ILLUSTRATIVE — not compiled or run in this repo.
//
// Shape of an iOS verifier. It reads the same canonical document as every other platform
// and drives XCTest. Nothing here is generated by the skill: this file is written once,
// by whoever owns this toolchain, and changes when XCTest changes — not when a contract does.

import XCTest

struct Requirement: Decodable {
    let id: String, statement: String
    let observe: String?, expect: [String: AnyCodable]?
    let scenario: Scenario?, needs: [String]?
    let binds: Bool?, reason: String?
}

final class ContractVerifier: XCTestCase {

    func testContract() throws {
        let doc = try CanonicalDocument.load("Button.ios.canonical.json")
        let capability = Capability.current            // declared in capability.json

        for req in doc.requirements {
            // 1 — does it bind here at all?
            if req.binds == false {
                record(.notApplicable(req, reason: req.reason!)); continue
            }
            // 2 — can this verifier observe what the requirement needs?
            if let missing = req.needs?.first(where: { capability.cannotObserve.keys.contains($0) }) {
                throw XCTSkip("\(req.id) — \(req.statement) — unverified: \(capability.cannotObserve[missing]!)")
            }
            // 3 — find a witness satisfying the scenario predicate, or construct one
            guard let witness = Witness.matching(req.scenario) ?? Witness.construct(req.scenario) else {
                throw XCTSkip("\(req.id) — unverified: no witness satisfies \(req.scenario!)")
            }
            // 4 — observe and adjudicate
            let element = try witness.mount()          // UIHostingController, forced layout
            try assertObservation(req, on: element)
        }
    }

    private func assertObservation(_ req: Requirement, on el: AccessibilityNode) throws {
        switch req.observe {
        case "role":   XCTAssertEqual(el.traitsRole, req.expect!["equals"]!.stringValue, req.statement)
        case "name":   XCTAssertFalse(el.label.isEmpty, req.statement)
        case "state":  XCTAssertTrue(el.states.contains(req.expect!["contains"]!.stringValue), req.statement)
        case "focus":  XCTAssertEqual(el.isFocusable, req.expect!["equals"]!.boolValue, req.statement)
        case "layout": XCTAssertGreaterThanOrEqual(min(el.frame.width, el.frame.height),
                                                   req.expect!["min"]!.doubleValue, req.statement)
        case "order":  XCTAssertEqual(el.children.map(\.zone), req.expect!["order"]!.stringArray, req.statement)
        default:       throw XCTSkip("\(req.id) — observe \(req.observe ?? "?") not implemented")
        }
    }
}

// Note the three-state result is native: XCTAssert* gives pass/fail, XCTSkip gives the third
// state with its reason, and all three land in xcresult with no custom reporting.
